name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate static files
        run: |
          # Verificar que solo haya archivos seguros en public/documents
          if [ -d "public/documents" ]; then
            find public/documents -type f ! -name "*.pdf" ! -name "*.md" ! -name ".htaccess" | while read file; do
              echo "⚠️  Warning: Non-PDF file found in documents: $file"
              exit 1
            done
          fi

          # Verificar que las imágenes tengan formatos seguros
          if [ -d "public/images" ]; then
            find public/images -type f ! -name "*.jpg" ! -name "*.jpeg" ! -name "*.png" ! -name "*.webp" ! -name "*.svg" | while read file; do
              echo "⚠️  Warning: Unsupported image format: $file"
              exit 1
            done
          fi

      - name: Build project
        run: npm run build

      - name: Copy CNAME file
        run: cp CNAME out/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
